camunda.bpm.client:
  # the URL pointing to the Camunda Platform Runtime REST API
  base-url: ${CAMUNDA_REST_BASE}
  # defines how many milliseconds the External Tasks are locked until they can be fetched again
  lock-duration: 10000
#  subscriptions:
#    scoreProvider: # topic name of the External Service Task
#      variable-names: [] # our business logic doesn't require any variables, so don't fetch them
#      process-definition-key: loan_process # only filter for External Tasks with this process definition key
#    loanGranter:
#        variable-names: customerId, creditScore # only fetch these two variables
#        process-definition-key: loan_process

# increase the log level of the application
logging.level.org.camunda.bpm.client: DEBUG
